#!/bin/bash
# Environment Variables Setup for Cloudflare Pages

echo "🔧 Etsy API Setup - Environment Variables Needed"
echo "================================================"
echo ""
echo "Your site is deployed but products aren't loading because"
echo "Cloudflare Pages needs your Etsy API credentials."
echo ""
echo "📋 COPY THESE COMMANDS:"
echo ""
echo "1. Go to Cloudflare Pages dashboard:"
echo "   https://dash.cloudflare.com"
echo ""
echo "2. Navigate to your project settings:"
echo "   Workers & Pages → croiconcrete-site → Settings"
echo ""
echo "3. Scroll to 'Environment variables' section"
echo ""
echo "4. Click 'Add variable' and add BOTH of these:"
echo ""
echo "   Variable 1:"
echo "   Name: ETSY_API_KEY"
echo "   Value: [Paste your Etsy keystring here]"
echo ""
echo "   Variable 2:"
echo "   Name: ETSY_SHARED_SECRET"
echo "   Value: [Paste your Etsy shared secret here]"
echo ""
echo "5. After adding both, click 'Save'"
echo ""
echo "6. Go to 'Deployments' tab and click 'Retry deployment'"
echo ""
echo "✅ Your products will load after redeployment!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Where to find your Etsy credentials:"
echo "   1. Go to: https://www.etsy.com/developers/your-apps"
echo "   2. Click on your app name"
echo "   3. Copy:"
echo "      - Keystring → use as ETSY_API_KEY"
echo "      - Shared Secret → use as ETSY_SHARED_SECRET"
echo ""
echo "🧪 Test after deployment:"
echo "   Visit: https://croiconcrete.co.uk"
echo "   Products should load in ~30 seconds!"
echo ""
