#!/bin/bash
# Deploy to Cloudflare Pages - Manual Upload Method

echo "🚀 CroiConcrete - Ready for Cloudflare Pages"
echo "============================================="
echo ""
echo "✅ All files are committed and ready!"
echo ""
echo "📊 Files to deploy:"
wc -l index.html functions/listings.js _headers
echo ""
echo "🎯 DEPLOY NOW (3 Easy Steps):"
echo ""
echo "1. Go to: https://dash.cloudflare.com/[YOUR_ACCOUNT_ID]/pages"
echo ""
echo "2. If this is a NEW project:"
echo "   - Click 'Create a project'"
echo "   - Click 'Upload assets'"
echo "   - Name it: croiconcrete-site"
echo "   - Drag ALL files from this folder into the upload area"
echo "   - Click 'Deploy site'"
echo ""
echo "3. If project EXISTS (croiconcrete.co.uk):"
echo "   - Click on 'croiconcrete-site' project"
echo "   - Click 'Create deployment'"
echo "   - Drag ALL files from this folder"
echo "   - Click 'Deploy'"
echo ""
echo "📁 Your project folder is:"
echo "   $(pwd)"
echo ""
echo "✨ After upload, your site will be live in ~30 seconds!"
echo ""
echo "🔗 Site URLs:"
echo "   - Production: https://croiconcrete.co.uk"
echo "   - Preview: https://croiconcrete-site.pages.dev"
echo ""
echo "💡 TIP: You can drag the entire folder into Cloudflare Pages!"
