#!/bin/bash
# Fix: Redeploy with Functions

echo "🔧 Fix: Deploy Functions to Cloudflare Pages"
echo "============================================="
echo ""
echo "The /listings endpoint is returning 404 because Cloudflare Pages"
echo "didn't recognize the functions/ folder in your deployment."
echo ""
echo "QUICKEST FIX (2 options):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 1: Manual Redeploy (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Workers & Pages → croiconcrete-site"
echo "3. Click: 'Create deployment'"
echo "4. IMPORTANT: Drag the ENTIRE folder including 'functions/'"
echo "   Path: /Users/cal/Documents/Projects/croiconcrete-site"
echo "5. Make sure you see 'functions' in the upload list"
echo "6. Click: 'Deploy'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 2: Use Wrangler (If you can fix npm permissions)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Fix npm permissions first:"
echo "  sudo chown -R \$(whoami) /opt/homebrew/lib/node_modules"
echo ""
echo "Then:"
echo "  npm install -g wrangler"
echo "  wrangler login"
echo "  wrangler pages deploy . --project-name=croiconcrete-site"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ After redeployment:"
echo "   Test: curl https://croiconcrete.co.uk/listings"
echo "   Should return JSON product data (not 404)"
echo ""
echo "📁 Files to make sure are included:"
ls -la functions/
echo ""
